### PR TITLE
Add install_requires to setup.py so pip install dependencies

### PR DESCRIPTION
**Pull request by non-Jedi**

### CODE REVIEW

**Comment by CalebBell** [comment]
Hmm, I didn't realize I didn't include these directives! I included them in my thermo library, but not for either this or my heat transfer library! Do you have any reason for choosing those specific old versions? If not, I'll change this to the latest versions I'm aware of working.

Sincerely,
Caleb

**Comment by non-Jedi** [comment]
Picked those versions because those were the ones specified in requirements.txt. If you update them, I recommend updating that file, too.

Thanks for putting this together by the way. Thinking about using this with ipynb to include calcs in reports.

**Comment by CalebBell** [comment]
Right, I remember searching through the changelogs to find the oldest versions that should be supported now. Thank you, Adam! I'll get this out on pypi this weekend for sure.
For reports, you might want to give a go with the new units handling functionality from [pint](https://fluids.readthedocs.io/fluids.units.html) (an optional dependency). It's new and hasn't made it into the tutorial yet. I'd appreciate any feedback on it!

**Comment by non-Jedi** [comment]
Great to hear you're trying to make this compatible with pint! I use it for all my on-the-fly calcs already.

**Pull request merged**
