### PR TITLE
Napier correction for steam relief bugfix

### PR DESCRIPTION
**Pull request by andr1976**
See p. 73 in API 520 (2014 rev.) , at pressure below 10,339 kPa KN = 1

### CODE REVIEW

**Comment by andr1976** [comment]
@CalebBell please review - merry X-mas

**Comment by CalebBell** [comment]
Hi Anders,

That's not good. Thank you for noticing the issue. Your fix had a small typo in the ("=<" instead of the correct ">="), and one of my test cases was itself exposing the issue, so I fixed the example. I also updated the docstring to describe this.

I have cut a new release, 1.0.15, with the fix. You caught me right as I was sitting down to work on open source - I will rarely be able to be this speedy in the future :)

Thanks, and happy holidays to you too!

Caleb

**Comment by andr1976** [comment]
Hi Caleb, 

I have worked my way through the vapor relief equations and for now everything seems to be ok (except for the small fix), next up is the liquid relief. I have started ported a pile of VBA code to python and we actually did all this in VBA a loong time ago, now I am trying to use as many open source packages as I can (for now thermo/fluids and coolprop)  to provide as much coverage as possible to easy the burden of porting all the other code.  This is probaly not the last you will hear from me :-) 
Btw I think you have done an excellent job strucuring the code and providing documentation etc. 

Anders

**Comment by CalebBell** [comment]
Thanks! I believe that many eyes make all bugs shallow, and that is one strength of open source.

**Pull request merged**
